/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>

#include "publications.h"

bool_t
init_publication_1_svc(int *result, struct svc_req *rqstp)
{

	printf("INIT\n");
	bool_t retval=1;

	/*
	 * insert server code here
	 */
	 mkdir("./publications", 0777);
	 printf("Initialization of the publication storage system was successful\n");
	 printf("--------------------------\n"); //Separator

	return retval;
}

bool_t
get_publication_1_svc(char *topic, char *broker_buffer, int *result,  struct svc_req *rqstp)
{
	bool_t retval=1;

	printf("GET\n");

	printf("The topic received was: %s\n", topic);

	 char file_path[strlen("./publications/")+strlen(topic)];
	 sprintf(file_path, "%s%s", "./publications/",topic);
	 int fd=open(file_path, O_RDONLY);
	 if(fd==-1){
		 perror("Error opening the file or there is no file for the given topic.\n");
	 }
	 else{
		 if((read(fd, broker_buffer, 1024)==-1)){
			 perror("Error reading the file.\n");
		 }
		 printf("Value on the buffer: %s\n", broker_buffer);
		 if(((close(fd)))==-1){
			 perror("Error closing the file descriptor.\n");
		 }
	 }
	 printf("--------------------------\n"); //Separator

	return retval;
}

bool_t
set_publication_1_svc(char *topic, char *text, int *result,  struct svc_req *rqstp)
{
	bool_t retval=1;

	printf("SET\n");

	/*
	 * insert server code here
	 */

	 printf("The topic received was: %s\n", topic);
	 printf("The text received was: %s\n", text);

	 char file_path[strlen("./publications/")+strlen(topic)];

	 sprintf(file_path, "%s%s", "./publications/",topic);
	 printf("Value of filepath: %s\n", file_path);
	 int fd=open(file_path, O_CREAT|O_RDWR|O_TRUNC, 0777);
	 if(fd==-1){
		 perror("The file cannot be created.\n");
	 }
	 else{
		 char write_buf[1024];
		 bzero(write_buf, sizeof(write_buf));
		 strcpy(write_buf, text);
		 if(((write(fd, write_buf, 1024)))==-1){
			 perror("The topic cannot be written.\n");
		 }
		 if(((close(fd)))==-1){
			 perror("Error closing the file descriptor.\n");
		 }
	 }
	 printf("--------------------------\n"); //Separator
	return retval;
}

int
publications_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
