/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "publications.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
init_publication_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, INIT_PUBLICATION, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
get_publication_1(char *arg1, char **clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, GET_PUBLICATION,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
set_publication_1(char *arg1, char *arg2, int *clnt_res,  CLIENT *clnt)
{
	set_publication_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, SET_PUBLICATION, (xdrproc_t) xdr_set_publication_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
