/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>

#include "publications.h"

bool_t
init_publication_1_svc(int *result, struct svc_req *rqstp)
{
	bool_t retval=1;

	/*
	 * insert server code here
	 */
	 mkdir("./publications", 0777);

	return retval;
}

bool_t
get_publication_1_svc(char *topic, char *broker_buffer, int *result,  struct svc_req *rqstp)
{
	bool_t retval=1;

	 char * file_path="";
	 sprintf(file_path, "%s%s", "./publications/",topic);
	 int fd=open(file_path, O_RDONLY);
	 if(fd==-1){
		 perror("There is no file for the given topic.\n");
	 }
	 else{
		 if((read(fd, broker_buffer, 1024)==-1)){
			 perror("Error reading the file.\n");
		 }
	 }

	return retval;
}

bool_t
set_publication_1_svc(char *topic, char *text, int *result,  struct svc_req *rqstp)
{
	bool_t retval=1;

	/*
	 * insert server code here
	 */
	 char * file_path="";
	 sprintf(file_path, "%s%s", "./publications/",topic);
	 int fd=open(file_path, O_CREAT|O_WRONLY|O_TRUNC);
	 if(fd==-1){
		 perror("The file cannot be created.\n");
	 }
	 else{
		 if(((write(fd, text, 1024)))==-1){
			 perror("The topic cannot be written.\n");
		 }
	 }
	return retval;
}

int
publications_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
