/*
This code will contain the functions defined in the library rpc_functions.h that will be called by
the broker to communicate with the RPC and use its functionalities.
*/
#include "publications.h"
#include "rpc_functions.h"

//The functions will follow the exact same scheme as the file automatically generated by the rpcgen command.

//Function to initialize the service (generate the directory for the storage system):
void init_service(char *host){

	printf("RPC: Calling init.\n");

	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;

	#ifndef	DEBUG
		clnt = clnt_create (host, PUBLICATIONS, PUBLICATIONSVER, "tcp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif

	//Calling the server for the required functionality:
	retval_1 = init_publication_1(&result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif

}

//Function to obtain the text of the given topic into the buffer:
void get_rpc_publication(char * topic, char * buffer, char * host){

	printf("RPC: Calling get.\n");

	CLIENT *clnt;
	enum clnt_stat retval_2;
	char * result_2;
	char *get_publication_1_arg1=topic;

	#ifndef	DEBUG
		clnt = clnt_create (host, PUBLICATIONS, PUBLICATIONSVER, "tcp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif

	//Calling the server for the required functionality:
	retval_2 = get_publication_1(get_publication_1_arg1, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	printf("Contents of the text obtained: %s\n", result_2);

	//Copying the result of the RPC call into the local buffer:
	strcpy(buffer, result_2);

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif

}

//Function to generate a new file with the given topic and text:
void set_rpc_publication(char * topic, char * text, char * host){

	printf("RPC: Calling set.\n");

	CLIENT *clnt;
	enum clnt_stat retval_3;
	int result_3;
	char *set_publication_1_arg1=topic;
	char *set_publication_1_arg2=text;

	#ifndef	DEBUG
		clnt = clnt_create (host, PUBLICATIONS, PUBLICATIONSVER, "tcp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif

	//Calling the server for the required functionality:
	retval_3 = set_publication_1(set_publication_1_arg1, set_publication_1_arg2, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif

}
